[tool.poetry]
name = "neuralnetworks"
version = "0.1.0"
description = ""
authors = ["Christian Coenen <coenen.christian@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8.3"
tensorflow = "~=2.3.1"
Pillow = "~=7.2.0"
moviepy = "~=1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
